apiVersion: v1
kind: ConfigMap
metadata:
  name: normalizer-config
  namespace: nas
data:
  KAFKA_BROKERS: "kafka:29092"
  KAFKA_TOPIC_RAW: "fixm.raw"
  KAFKA_TOPIC_NORMALIZED: "fixm.normalized"
  KAFKA_TOPIC_NORMALIZED_DLQ: "fixm.normalized.dlq"
  KAFKA_GROUP: "normalizer"
  OPS_ADDR: ":2112"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: normalizer
  namespace: nas
  labels: { app: normalizer }
spec:
  replicas: 1
  selector: { matchLabels: { app: normalizer } }
  template:
    metadata:
      labels: { app: normalizer }
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2112"
    spec:
      containers:
        - name: normalizer
          image: nas-normalizer:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef: { name: normalizer-config }
          ports:
            - containerPort: 2112
              name: ops
          livenessProbe:
            httpGet: { path: /healthz, port: 2112 }
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /readyz, port: 2112 }
            initialDelaySeconds: 5
            periodSeconds: 10