apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
patches:
  - target:
      kind: StatefulSet
      name: kafka
    patch: |
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 500Gi
  - target:
      kind: PersistentVolumeClaim
      name: redis-data
    patch: |
      - op: replace
        path: /spec/resources/requests/storage
        value: 2Gi
  - target:
      kind: ConfigMap
      name: api-config
    patch: |
      - op: replace
        path: /data/GO_ENV
        value: prod
  - target:
      kind: Service
      name: web
    patch: |
      - op: add
        path: /spec/type
        value: LoadBalancer
      - op: replace
        path: /spec/ports/0/port
        value: 15000